import Navbar from '../components/layout/Navbar';
import Footer from "../components/layout/Footer"
import './globals.css'
import { Sora } from "next/font/google";
import Faq from '../components/layout/Faq';

const inter = Sora({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Faq />
        <Footer />
      </body>
    </html>
  )
}
